package com.example.recyclerequestapp.model;

import com.google.gson.annotations.SerializedName;
import java.io.Serializable; // Import Serializable

public class RecyclableItem implements Serializable { // Implements Serializable

    @SerializedName("item_id")
    private int id;
    @SerializedName("item_name")
    private String itemName;
    @SerializedName("price_per_kg")
    private Double pricePerKg;

    // Default constructor (IMPORTANT for Gson deserialization)
    public RecyclableItem() {
    }

    // Constructor for adding new items (without 'id', as it's typically auto-generated by backend)
    public RecyclableItem(String itemName, Double pricePerKg) {
        this.itemName = itemName;
        this.pricePerKg = pricePerKg;
    }

    // Constructor for existing items (with 'id', typically for updates or retrieval)
    public RecyclableItem(int id, String itemName, Double pricePerKg) {
        this.id = id;
        this.itemName = itemName;
        this.pricePerKg = pricePerKg;
    }

    // Getters
    public int getId() { return id; }
    public String getItemName() { return itemName; }
    public Double getPricePerKg() { return pricePerKg; }

    // Setters (IMPORTANT for building objects from form input and for Retrofit)
    public void setId(int id) { this.id = id; }
    public void setItemName(String itemName) { this.itemName = itemName; }
    public void setPricePerKg(Double pricePerKg) { this.pricePerKg = pricePerKg; }

    // --- Removed Parcelable implementation methods ---
    // (No describeContents(), writeToParcel(), or CREATOR for Serializable)
}